### ISSUE TITLE
#10 Cart 구현 목표

### ISSUE THREAD

**Issue by commety** [GDSC-PKNU-Official/24_2_BE_Beginner_Week2_UNOFFICIAL#12]
1. `cart` 클래스 변수가 `List<Map<Product, Integer>>` 이런 식으로 되야 할 거 같습니다.
=> 이 구현이 어렵다면 stock 필드를 삭제하겠습니다. 😢
2. `addProduct`, `deleteProduct` 메서드는 사용자로부터
long 타입 productId (상품 id)와 int 타입 orderQuantity(주문 수량)을 입력받아
유효성 검사 후 올바른 Product를 저장하는 것이 좋아 보입니다.
3. CartDto 역할이 모호합니다.
CartDto가 단순 데이터 전달을 넘어 상품을 매핑해서 가격 정보와 재고 정보를 반환하는 메서드까지 가지고 있습니다.
만약, DTO를 사용하겠다면 클래스명을 CartDto가 아니라 ProductMappingDto로 변경하고
Product 객체를 매핑하기 위한 클래스로 사용하는 것이 좋아 보입니다.
## ✅ ToDo
- [x] Cart가 Product를 담을 적절한 자료구조 만들기
- [x] 사용자로부터 받은 long 타입 productId로 알맞은 Product 찾기 
(ProductList는 ProductDao로부터 읽어와서 main에 `static final List<Product>` 형태로 저장되어 있습니다. 
우선, 매개변수로 ProductList도 받아서 유효성 검사 후 매핑하시면 될거 같습니다!)
- [x] CartDto 이름 변경 또는 사용 안 함

**Comment by xxubin04** [comment]
회성님, 1번에 cart 클래스 변수를 `HashMap<String, Integer>` -> `List<Map<Product, Integer>> ` 로 변경하고 있습니다! 그러면 OrderSheet 클래스에서 매개변수로 받는 `HashMap<String, Integer> orderedProductHashMap`도 바꿔야 하는게 맞는걸까요?

**Comment by commety** [comment]
네! 맞습니다!
`orderedProductHashMap`은 Cart 클래스의 `cart`라고 생각하시면 됩니다.
추후 product 매핑이 제대로 동작한다면 OrderSheet 구현을 변경할 예정입니다.

**Comment by commety** [comment]
#14 
Product 매핑 
1. productList에서 productId와 일치하는 Product 찾기
2. 찾은 Product 의 stock을 가져와 `stock >= quantity` 를 만족하는 지 검사
3. 1,2 만족하면 `Map<Product, Integer>`에 저장
4. `List<Map<Product, Integer>>`에 저장

**Comment by xxubin04** [comment]
> #14 Product 매핑
> 
> 1. productList에서 productId와 일치하는 Product 찾기
> 2. 찾은 Product 의 stock을 가져와 `stock >= quantity` 를 만족하는 지 검사
> 3. 1,2 만족하면 `Map<Product, Integer>`에 저장
> 4. `List<Map<Product, Integer>>`에 저장

엇 정신없이 구현하다보니 이 부분을 안 보면서 했네요.. 지금이라도 빠르게 반영해두겠습니다!

**Comment by commety** [comment]
헉,, 혹시 PR에 반영이 안 되어 있었나요?
제가 그냥 머지해버렸는데 반영이 안 되었다면 revert 하겠습니다...

**Comment by xxubin04** [comment]
엇 3번에 Map에 저장하는건 cart에 없는 새로운 상품인 경우에만 저장하는 것을 말씀하시는 거라면 구현되어 있습니다!

그리고 4번은 cart에 저장하는 것을 말씀하시는건가요?!

**Comment by commety** [comment]
네 맞습니다!

**Comment by xxubin04** [comment]
그렇다면 다 반영된 것 같아요! 늦은 시간에 봐주셔서 감사합니다!!

CartDto는 삭제해도 괜찮을까요??

**Comment by commety** [comment]
네 로직에 사용되지 않는다면 삭제해도 상관없을 것 같아요!

**Comment by commety** [comment]
CartDto까지 삭제한 commit을 PR에 올려주시면 바로 머지하고 나머지 commandHandler가 요구하는 메서드 작성하겠습니다

**Comment by xxubin04** [comment]
헉 저 잘못 올렸어요..ㅠㅠ

**Comment by xxubin04** [comment]
이제 남은 게 어떤 것들이 있는지 간략하게 말씀해주실 수 있을까요?? 남는 것들 중에서 최대한 하겠습니다!
commandHandler에서 오류나는 부분 수정할까요??

**Comment by commety** [comment]
우선 제가 빠르게 Customer와 Cart 클래스에 필요한 메서드 작성 중입니다!
조금 늦을 수도 있으니 2시 30분 내 PR 없거나 피곤하시면 주무시러 가는 게 좋을 거 같습니다 하하

**Comment by xxubin04** [comment]
아ㅠㅠ 제가 너무 몰라서 늦게 올려서 죄송합니다..ㅠㅠ 저 때문에 회성님도 못 주무시고... 우선 깨어있을테니 필요하시다면 언제나 꼭 말씀해주세요😭😭
